#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --rate 144 &
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &
dunst &
feh --bg-fill --randomize  ~/Downloads/wallpapers/* &
$HOME/.config/polybar/launch.sh

wmname LG3D

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width        2
bspc config focused_border_color "#C9CBFF"
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Cider desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv desktop='^4'
bspc rule -a code desktop='^1'
